spring.application.name=webapp
spring.profiles.active=dev
spring.mustache.suffix=.html

# spring.datasource.url=jdbc:h2:mem:mqm_db
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.web.error.whitelabel.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/mqm
spring.datasource.username=root
spring.datasource.password=mqmurjc
spring.jpa.hibernate.ddl-auto=update

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# security
server.port = 8443
server.ssl.key-store = classpath:keystore.jks
server.ssl.key-store-password = password
server.ssl.key-password = secret

utilityservice.url=${UTILITY_SERVICE_URL:http://localhost:8080/api/v1/}