spring.application.name=webapp
spring.mustache.suffix=.html

# Use in-memory DB for integration profile
spring.datasource.url=jdbc:h2:mem:mqm_integration;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Disable SSL for local integration runs
server.ssl.enabled=false
