spring.application.name=webapp
spring.mustache.suffix=.html

# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mqm_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true