spring.application.name=webapp
spring.profiles.active=dev
spring.mustache.suffix=.html

spring.datasource.url=jdbc:h2:mem:mqm_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.web.error.whitelabel.enabled=false


# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# security
server.port = 8443
server.ssl.key-store = classpath:keystore.jks
server.ssl.key-store-password = password
server.ssl.key-password = secret

# mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meloquitandelasmanos.admin@gmail.com
# spring.mail.password in application-dev.properties

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
